### PR TITLE
Fixed module name inconsistency in typescript defintions

### PR DESCRIPTION
**Pull request by fela98**
Solves typescript error.

### CODE REVIEW

**Comment by NicoAiko** [comment]
@sdnetwork ehm. What's the status here?

**Comment by NicoAiko** [comment]
@fela98 Is there a reason why you set the encoding to `latin1` and `ISO8859_1`?

**Comment by sdnetwork** [comment]
For me no reason to change default encoding ! @fela98 why this change ?
For typescript you're right

**Comment by fela98** [comment]
Hi, Sorry

Such a long time ago that I forgot this PR and pushed more to my master.

Use new PR #4 instead

**Pull request closed without merging**
